name: Build App

on: [push]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
          - target: i686-pc-windows-msvc
            prefix: _32bit

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build project
        run: |
          rustup target add ${{ matrix.target }}
          cargo build --release --target ${{ matrix.target }}

      - name: Add prefix
        if: matrix.prefix
        shell: powershell
        run: |
          $binaries = Get-ChildItem -Path .\target\${{ matrix.target }}\release\* -Include *.dll,*.exe
          $binaries | Rename-Item -NewName { $_.Name + "${{ matrix.prefix }}" };

      - name: Upload ${{ matrix.target }} artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-binaries
          path: |
            target/${{ matrix.target }}/release/*.exe
            target/${{ matrix.target }}/release/*.dll
          if-no-files-found: error

  release:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v5
        with:
          pattern: "*-binaries"
          path: dist
          merge-multiple: true

      - name: Generate zip bundle
        run: 7z a -tzip Invisiwind.zip .\hide.ahk .\dist\*.dll .\dist\*.exe

      - name: Build Installer
        run: iscc .\Misc\inno.iss

      - name: Publish latest pre-release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          prerelease: true
          generate_release_notes: true
          files: |
            Invisiwind.zip
            Misc/Output/InvisiwindInstaller.exe

      - if: startsWith(github.ref, 'refs/tags/v')
        name: Publish tagged release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          generate_release_notes: true
          files: |
            Invisiwind.zip
            Misc/Output/InvisiwindInstaller.exe
