name: Build App

on: [push]

jobs:
  build-arm:
    runs-on: windows-11-arm
    continue-on-error: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build
        run: cargo build --release

  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build amd64
        run: cargo build --release

      - name: Build x86
        run: |
          rustup target add i686-pc-windows-msvc
          cargo build --release -p payload --target i686-pc-windows-msvc

      - name: Copy x86 binaries
        shell: powershell
        run: Copy-Item -Path .\target\i686-pc-windows-msvc\release\utils.dll -Destination .\target\release\utils32.dll

      - name: Generate zip bundle
        run: 7z a -tzip Invisiwind.zip .\hide.ahk .\target\release\*.dll .\target\release\*.exe

      - name: Build Installer
        run: iscc .\Misc\inno.iss

      - name: Publish latest pre-release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          prerelease: true
          generate_release_notes: true
          files: |
            Invisiwind.zip
            Misc/Output/InvisiwindInstaller.exe

      - if: startsWith(github.ref, 'refs/tags/v')
        name: Publish tagged release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          generate_release_notes: true
          files: |
            Invisiwind.zip
            Misc/Output/InvisiwindInstaller.exe
