name: Build App

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Project
        run: cargo build --release

      - name: Generate zip bundle
        run: 7z a -tzip Invisiwind.zip .\hide.ahk .\target\release\*.dll .\target\release\*.exe

      - name: Build Installer
        run: iscc .\Misc\inno.iss

      - name: Publish latest pre-release
        uses: softprops/action-gh-release@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: latest
          prerelease: true
          files: |
            Invisiwind.zip
            Misc/Output/InvisiwindInstaller.exe

      - if: startsWith(github.ref, 'refs/tags/v')
        name: Publish tagged release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            Invisiwind.zip
            Misc/Output/InvisiwindInstaller.exe
